spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/checkout
    username: postgres
    password: 2807
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: select 1
    jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          show_sql: true
          use_sql_comments: true
          jdbc:
            lob:
              non_contextual_creation: true
